nome = input ("qual é o seu nome?")
altura = input ("qual é a sua altura")
idade = input ("qual é a sua idade?")
estudante = input("você é estudante?")
print("Bem vindo " , nome )
print("a sua idade é " , idade )
print( "sua altura é" , altura )
print(estudante)
